baseURL = "/"
languageCode = "en-us"
title = "Isham Araia's Blog"
slogan = "Posts about cloud native & distributed systems, Linux internals and more"
rssLimit = 20
copyright = "2023 Isham Araia All rights reserved"
minify = false

[Author]
  name = "sharadcodes"
  email = "me@ish-ar.io"

[permalinks]
  posts = "/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]